#!/usr/bin/perl

#
# plugin_large - A 'check plugin' that just generates tons of output
#
# author:  James Hunt <jhunt@synacor.com>
# created: 2013-04-04
#
# This script is awesome.  It doesn't do anything except generate
# large strings of alternating letters.
#
# Try the following examples to get a feel for it:
#
#   ./runway/plugin_large 2 4 6 8 10
#   ./runway/plugin_large 255 1
#
# The alternating letters make it easy to detect fenceposts, as in the
# second example above.  The 'I' should be the 256th position.
#
# This check is used to test NLMA's ability to handle plugins that
# generate large amounts of output (larger than a pipe's worth).
# It also exercises the 4k upper limit on plugin output.
#

my @letters = qw/. I _ v/;

do { my $f = select STDOUT; $| = 1; select $f };

for ($i = 0; $i < @ARGV; $i++) {
	print $letters[$i % @letters] x $ARGV[$i];
}
print "\n";
exit 0;
